# Generated by Django 4.1.7 on 2023-03-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to=None, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
