# Generated by Django 4.1.7 on 2023-03-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Фото Категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='body_material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='coating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wind_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useful',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='useful_files/'),
        ),
    ]
