# Generated by Django 4.1.7 on 2023-03-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_bracket_outreach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='luminous_flux',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Световой поток, лм'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power_consumption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Потребляемость, вт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер, ДxШxВ'),
        ),
        migrations.AlterField(
            model_name='useful',
            name='subtitle',
            field=models.TextField(),
        ),
    ]
