# Generated by Django 4.1.7 on 2023-03-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_luminous_flux_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='curve_power_light',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кривая Силы Света'),
        ),
        migrations.AddField(
            model_name='product',
            name='light_angle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Угол светового потока, градусы'),
        ),
        migrations.AddField(
            model_name='request',
            name='additional_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дополнительное поле'),
        ),
    ]
